"""empty message

Revision ID: 1ef1d2eb7e4c
Revises: b6bca1d9d43f
Create Date: 2023-02-21 14:41:19.098357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef1d2eb7e4c'
down_revision = 'b6bca1d9d43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_img', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_img')

    # ### end Alembic commands ###
