"""empty message

Revision ID: 2000385bad78
Revises: ba90cfc6e4ab
Create Date: 2023-02-20 22:21:15.286028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2000385bad78'
down_revision = 'ba90cfc6e4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=4000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
