"""empty message

Revision ID: 59e4a73f1d17
Revises: f531ccb73a3e
Create Date: 2023-03-01 13:33:46.999424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e4a73f1d17'
down_revision = 'f531ccb73a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('style_nm', sa.String(length=20), nullable=True),
    sa.Column('pan_nm', sa.String(length=100), nullable=True),
    sa.Column('pan_color', sa.String(length=10), nullable=True),
    sa.Column('ls_nm', sa.String(length=100), nullable=True),
    sa.Column('ls_color', sa.String(length=10), nullable=True),
    sa.Column('sq_nm', sa.String(length=100), nullable=True),
    sa.Column('sq_color', sa.String(length=10), nullable=True),
    sa.Column('pt_nm', sa.String(length=100), nullable=True),
    sa.Column('pt_color', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_style_nm'), ['style_nm'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_style_nm'))

    op.drop_table('style')
    # ### end Alembic commands ###
