"""empty message

Revision ID: 904eb6110339
Revises: 59e4a73f1d17
Create Date: 2023-03-05 11:15:12.841860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904eb6110339'
down_revision = '59e4a73f1d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_style_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
