"""empty message

Revision ID: b6bca1d9d43f
Revises: 2000385bad78
Create Date: 2023-02-21 10:51:12.692031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bca1d9d43f'
down_revision = '2000385bad78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_caption', sa.String(length=200), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('img_caption')

    # ### end Alembic commands ###
