"""empty message

Revision ID: cb362088faec
Revises: 904eb6110339
Create Date: 2023-03-05 11:38:17.800538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb362088faec'
down_revision = '904eb6110339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_inspire', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('style_inspire')

    # ### end Alembic commands ###
